export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const DELETE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";
export const DELETE_ALL_PRODUCTS_FROM_CART = "DELETE_ALL_PRODUCTS_FROM_CART";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";
export const EMPTY_PRODUCTS = "EMPTY_PRODUCTS";

export const GET_FAVORITES = "GET_FAVORITES";
export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const EMPTY_PRODUCT = "EMPTY_PRODUCT";

export const GET_SHOPPING_BAG = "GET_SHOPPING_BAG";
export const GET_SHOPPING_BAG_SUCCESS = "GET_SHOPPING_BAG_SUCCESS";
export const GET_SHOPPING_BAG_FAIL = "GET_SHOPPING_BAG_FAIL";

export const ADD_TO_SHOPPING_BAG = "ADD_TO_SHOPPING_BAG";
export const ADD_TO_SHOPPING_BAG_SUCCESS = "ADD_TO_SHOPPING_BAG_SUCCESS";
export const ADD_TO_SHOPPING_BAG_FAIL = "ADD_TO_SHOPPING_BAG_FAIL";

export const REMOVE_FROM_SHOPPING_BAG = "REMOVE_FROM_SHOPPING_BAG";
export const REMOVE_FROM_SHOPPING_BAG_SUCCESS =
	"REMOVE_FROM_SHOPPING_BAG_SUCCESS";
export const REMOVE_FROM_SHOPPING_BAG_FAIL = "REMOVE_FROM_SHOPPING_BAG_SUCCESS";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const ADD_ORDER = "ADD_ORDER";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
